# Generated by Django 4.2.1 on 2023-05-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_musicgeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_file', models.FileField(blank=True, max_length=254, null=True, upload_to='StockPrediction/')),
            ],
        ),
    ]
