# Generated by Django 4.2.1 on 2023-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_options_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
